### ISSUE TITLE
gitlab-ci.yml configuration

### ISSUE THREAD

**Issue by L-U-C-K-Y** [lgaticaq/semantic-release-gitlab-registry#3]
Hi Leonardo

I've been trying to set up the .gitlab-ci.yml file and I was not able to successfully run it.

It seems that the problem is that the docker build command is not available. Do you know what the issue could be?

Here is my current config:

```
image: docker:19.03.8

stages:
- build

variables:
  # When using dind service, we need to instruct docker, to talk with
  # the daemon started inside of the service. The daemon is available
  # with a network connection instead of the default
  # /var/run/docker.sock socket. docker:19.03.1 does this automatically
  # by setting the DOCKER_HOST in
  # https://github.com/docker-library/docker/blob/d45051476babc297257df490d22cbd806f1b11e4/19.03.1/docker-entrypoint.sh#L23-L29
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services.
  #
  # Note that if you're using GitLab Runner 12.7 or earlier with the Kubernetes executor and Kubernetes 1.6 or earlier,
  # the variable must be set to tcp://localhost:2376 because of how the
  # Kubernetes executor connects services to the job container
  # DOCKER_HOST: tcp://localhost:2376
  #
  # Specify to Docker where to create the certificates, Docker will
  # create them automatically on boot, and will create
  # `/certs/client` that will be shared between the service and job
  # container, thanks to volume mount from config.toml
  DOCKER_TLS_CERTDIR: "/certs"
  
services:
  - docker:19.03.8-dind

before_script:
  - docker info

release:
  stage: build
  image: node:latest
  before_script:
    - node -v
    - npm install
    - docker build -t $CI_REGISTRY_IMAGE .
  script:
    - npx semantic-release
```

When trying to run:

```
$ docker build -t $CI_REGISTRY_IMAGE .
55 /bin/bash: line 99: docker: command not found
```

Cheers!

**Comment by lgaticaq** [comment]
Try install the docker client in before_script. This is my gitlab job:

```yml
release:
  image: node:12.16.1-alpine
  stage: deploy
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - apk add --no-cache docker git
    - docker build -t $CI_REGISTRY_IMAGE .
  script:
    - npx semantic-release
  only:
    - master
```

**Comment by L-U-C-K-Y** [comment]
Hi @lgaticaq 

Thanks for your help, it worked!

Fortunately, adding docker to alpine is quite straight-forward. Installing docker to a node image is trickier, but I found CircleCI images that have docker already built-in: https://circleci.com/docs/2.0/circleci-images/

Also, I've added the variables in the beginning:

```
variables:
  DOCKER_DRIVER: overlay2
  #DOCKER_TLS_CERTDIR: "/certs" # Does not work
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
```
